import { Employee, LeaveRequest, HandoverTask, PostLeaveNote, Notification, UserRole } from '@/types';

// Helper to determine user role based on reporting structure
function determineUserRole(email: string, allEmployees: Partial<Employee>[]): UserRole {
  // Exec email
  if (email === 'femi.adeola@curasel.com') return 'Exec';

  // HR email
  if (email === 'hr@curasel.com') return 'HR';

  // Check if anyone reports to this person (making them a Team Lead)
  const hasReports = allEmployees.some(emp => emp.tl_email === email);
  if (hasReports) return 'TeamLead';

  return 'Employee';
}

// Raw employee data from Google Sheets
const rawEmployees: Omit<Employee, 'user_role' | 'profile_image'>[] = [
  // EXEC - CEO
  {
    email: 'femi.adeola@curasel.com',
    full_name: 'Femi Adeola',
    tl_email: '',
    tl_name: '',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 1, 2020',
    team: 'Executive',
    role: 'Chief Executive Officer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 21,
    annual_taken: 5,
    annual_balance: 16,
    sick_entitlement: 10,
    sick_taken: 0,
    sick_balance: 10,
  },
  // Customer Success Lead - Kabir Adebayo (Male)
  {
    email: 'ka@curacel.com',
    full_name: 'Kabir Adebayo',
    tl_email: 'femi.adeola@curasel.com',
    tl_name: 'Femi A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 1, 2022',
    team: 'Customer Success',
    role: 'Customer Success Lead',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 4,
    annual_balance: 10,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  // Customer Success Manager - Amina Okoro
  {
    email: 'amina.okoro@curasel.com',
    full_name: 'Amina Okoro',
    tl_email: 'ka@curacel.com',
    tl_name: 'Kabir A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'February 3, 2024',
    team: 'Customer Success',
    role: 'Customer Success Manager',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'tunde.balogun@curasel.com',
    full_name: 'Tunde Balogun',
    tl_email: 'teni.adams@curasel.com',
    tl_name: 'Teni A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'May 12, 2023',
    team: 'Claims',
    role: 'Claims Lead',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'james.owen@curasel.com',
    full_name: 'James Owen',
    tl_email: 'ka@curacel.com',
    tl_name: 'Kabiru A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 10, 2025',
    team: 'Ops',
    role: 'Ops Analyst',
    country: 'Ghana',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'mariam.said@curasel.com',
    full_name: 'Mariam Said',
    tl_email: 'tunde.balogun@curasel.com',
    tl_name: 'Tunde B.',
    hr_email: 'hr@curasel.com',
    employment_date: 'September 5, 2024',
    team: 'Sales',
    role: 'Sales Manager',
    country: 'Kenya',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 4,
    annual_balance: 10,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'chioma.ude@curasel.com',
    full_name: 'Chioma Ude',
    tl_email: 'amina.okoro@curasel.com',
    tl_name: 'Amina O.',
    hr_email: 'hr@curasel.com',
    employment_date: 'August 21, 2022',
    team: 'Finance',
    role: 'Finance Lead',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'halima.idris@curasel.com',
    full_name: 'Halima Idris',
    tl_email: 'mariam.said@curasel.com',
    tl_name: 'Mariam S.',
    hr_email: 'hr@curasel.com',
    employment_date: 'March 17, 2024',
    team: 'Support',
    role: 'Support Lead',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 6,
    annual_balance: 8,
    sick_entitlement: 7,
    sick_taken: 3,
    sick_balance: 4,
  },
  {
    email: 'richard.mensa@curasel.com',
    full_name: 'Richard Mensa',
    tl_email: 'james.owen@curasel.com',
    tl_name: 'James O.',
    hr_email: 'hr@curasel.com',
    employment_date: 'October 14, 2022',
    team: 'Tech',
    role: 'DevOps Engineer',
    country: 'Ghana',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'susan.obieze@curasel.com',
    full_name: 'Susan Obieze',
    tl_email: 'ka@curacel.com',
    tl_name: 'Kabiru A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 2, 2025',
    team: 'Ops',
    role: 'Ops Associate',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'yusuf.musa@curasel.com',
    full_name: 'Yusuf Musa',
    tl_email: 'lekan.bello@curasel.com',
    tl_name: 'Lekan B.',
    hr_email: 'hr@curasel.com',
    employment_date: 'June 11, 2023',
    team: 'Finance',
    role: 'Finance Analyst',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'patience.udo@curasel.com',
    full_name: 'Patience Udo',
    tl_email: 'halima.idris@curasel.com',
    tl_name: 'Halima I.',
    hr_email: 'hr@curasel.com',
    employment_date: 'April 6, 2024',
    team: 'Support',
    role: 'Support Specialist',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 4,
    annual_balance: 10,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'victor.akin@curasel.com',
    full_name: 'Victor Akin',
    tl_email: 'susan.obieze@curasel.com',
    tl_name: 'Susan O.',
    hr_email: 'hr@curasel.com',
    employment_date: 'May 20, 2024',
    team: 'Ops',
    role: 'Ops Specialist',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'grace.tamuno@curasel.com',
    full_name: 'Grace Tamuno',
    tl_email: 'chioma.ude@curasel.com',
    tl_name: 'Chioma U.',
    hr_email: 'hr@curasel.com',
    employment_date: 'July 8, 2023',
    team: 'Claims',
    role: 'Claims Analyst',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 7,
    annual_balance: 7,
    sick_entitlement: 7,
    sick_taken: 2,
    sick_balance: 5,
  },
  {
    email: 'david.king@curasel.com',
    full_name: 'David King',
    tl_email: 'tunde.balogun@curasel.com',
    tl_name: 'Tunde B.',
    hr_email: 'hr@curasel.com',
    employment_date: 'August 2, 2024',
    team: 'Tech',
    role: 'Frontend Engineer',
    country: 'Kenya',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'abdul.kareem@curasel.com',
    full_name: 'Abdul Kareem',
    tl_email: 'amina.okoro@curasel.com',
    tl_name: 'Amina O.',
    hr_email: 'hr@curasel.com',
    employment_date: 'March 13, 2022',
    team: 'Ops',
    role: 'Field Engineer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 5,
    annual_balance: 9,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'blessing.ife@curasel.com',
    full_name: 'Blessing Ife',
    tl_email: 'halima.idris@curasel.com',
    tl_name: 'Halima I.',
    hr_email: 'hr@curasel.com',
    employment_date: 'December 1, 2024',
    team: 'Support',
    role: 'Support Agent',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'nana.boateng@curasel.com',
    full_name: 'Nana Boateng',
    tl_email: 'james.owen@curasel.com',
    tl_name: 'James O.',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 7, 2025',
    team: 'Ops',
    role: 'Ops Analyst',
    country: 'Ghana',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'oluchi.mbah@curasel.com',
    full_name: 'Oluchi Mbah',
    tl_email: 'grace.tamuno@curasel.com',
    tl_name: 'Grace T.',
    hr_email: 'hr@curasel.com',
    employment_date: 'May 23, 2024',
    team: 'Claims',
    role: 'Claims Officer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 4,
    annual_balance: 10,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'felix.ogwo@curasel.com',
    full_name: 'Felix Ogwo',
    tl_email: 'david.king@curasel.com',
    tl_name: 'David K.',
    hr_email: 'hr@curasel.com',
    employment_date: 'October 30, 2023',
    team: 'Tech',
    role: 'Product Designer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'esther.ajibade@curasel.com',
    full_name: 'Esther Ajibade',
    tl_email: 'blessing.ife@curasel.com',
    tl_name: 'Blessing I.',
    hr_email: 'hr@curasel.com',
    employment_date: 'April 15, 2023',
    team: 'Support',
    role: 'Training Facilitator',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'hassan.adamu@curasel.com',
    full_name: 'Hassan Adamu',
    tl_email: 'ka@curacel.com',
    tl_name: 'Kabiru A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'February 9, 2024',
    team: 'Ops',
    role: 'Ops Coordinator',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'janet.owusu@curasel.com',
    full_name: 'Janet Owusu',
    tl_email: 'richard.mensa@curasel.com',
    tl_name: 'Richard M.',
    hr_email: 'hr@curasel.com',
    employment_date: 'June 2, 2023',
    team: 'Tech',
    role: 'Systems Engineer',
    country: 'Ghana',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'paul.ekene@curasel.com',
    full_name: 'Paul Ekene',
    tl_email: 'chioma.ude@curasel.com',
    tl_name: 'Chioma U.',
    hr_email: 'hr@curasel.com',
    employment_date: 'May 14, 2024',
    team: 'Claims',
    role: 'Claims Reviewer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'kemi.ajayi@curasel.com',
    full_name: 'Kemi Ajayi',
    tl_email: 'halima.idris@curasel.com',
    tl_name: 'Halima I.',
    hr_email: 'hr@curasel.com',
    employment_date: 'July 18, 2023',
    team: 'Support',
    role: 'Support Analyst',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 4,
    annual_balance: 10,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'samuel.yaro@curasel.com',
    full_name: 'Samuel Yaro',
    tl_email: 'victor.akin@curasel.com',
    tl_name: 'Victor A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'October 25, 2024',
    team: 'Ops',
    role: 'Ops Assistant',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'brian.korir@curasel.com',
    full_name: 'Brian Korir',
    tl_email: 'mariam.said@curasel.com',
    tl_name: 'Mariam S.',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 12, 2025',
    team: 'Sales',
    role: 'Sales Associate',
    country: 'Kenya',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'tolulope.femi@curasel.com',
    full_name: 'Tolulope Femi',
    tl_email: 'tunde.balogun@curasel.com',
    tl_name: 'Tunde B.',
    hr_email: 'hr@curasel.com',
    employment_date: 'March 29, 2023',
    team: 'Tech',
    role: 'Mobile Engineer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 6,
    annual_balance: 8,
    sick_entitlement: 7,
    sick_taken: 2,
    sick_balance: 5,
  },
  {
    email: 'vivian.ukonu@curasel.com',
    full_name: 'Vivian Ukonu',
    tl_email: 'grace.tamuno@curasel.com',
    tl_name: 'Grace T.',
    hr_email: 'hr@curasel.com',
    employment_date: 'April 3, 2024',
    team: 'Claims',
    role: 'Claims Associate',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'emma.kofi@curasel.com',
    full_name: 'Emma Kofi',
    tl_email: 'nana.boateng@curasel.com',
    tl_name: 'Nana B.',
    hr_email: 'hr@curasel.com',
    employment_date: 'November 10, 2024',
    team: 'Ops',
    role: 'Ops Trainee',
    country: 'Ghana',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'queen.abasi@curasel.com',
    full_name: 'Queen Abasi',
    tl_email: 'susan.obieze@curasel.com',
    tl_name: 'Susan O.',
    hr_email: 'hr@curasel.com',
    employment_date: 'August 7, 2023',
    team: 'Ops',
    role: 'Ops Analyst',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'harry.dike@curasel.com',
    full_name: 'Harry Dike',
    tl_email: 'abdul.kareem@curasel.com',
    tl_name: 'Abdul K.',
    hr_email: 'hr@curasel.com',
    employment_date: 'October 15, 2022',
    team: 'Ops',
    role: 'Field Engineer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 4,
    annual_balance: 10,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'doris.ugwu@curasel.com',
    full_name: 'Doris Ugwu',
    tl_email: 'halima.idris@curasel.com',
    tl_name: 'Halima I.',
    hr_email: 'hr@curasel.com',
    employment_date: 'December 2, 2023',
    team: 'Support',
    role: 'Customer Support',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 2,
    sick_balance: 5,
  },
  {
    email: 'solomon.kofi@curasel.com',
    full_name: 'Solomon Kofi',
    tl_email: 'richard.mensa@curasel.com',
    tl_name: 'Richard M.',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 22, 2024',
    team: 'Tech',
    role: 'Cloud Engineer',
    country: 'Ghana',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'remi.ogunleye@curasel.com',
    full_name: 'Remi Ogunleye',
    tl_email: 'lekan.bello@curasel.com',
    tl_name: 'Lekan B.',
    hr_email: 'hr@curasel.com',
    employment_date: 'February 18, 2022',
    team: 'Finance',
    role: 'Senior Accountant',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 7,
    annual_balance: 7,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'linda.mutiso@curasel.com',
    full_name: 'Linda Mutiso',
    tl_email: 'mariam.said@curasel.com',
    tl_name: 'Mariam S.',
    hr_email: 'hr@curasel.com',
    employment_date: 'May 26, 2024',
    team: 'Sales',
    role: 'Sales Coordinator',
    country: 'Kenya',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'rosemary.joe@curasel.com',
    full_name: 'Rosemary Joe',
    tl_email: 'chioma.ude@curasel.com',
    tl_name: 'Chioma U.',
    hr_email: 'hr@curasel.com',
    employment_date: 'July 30, 2023',
    team: 'Claims',
    role: 'Senior Claims Analyst',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 5,
    annual_balance: 9,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'francis.ogaba@curasel.com',
    full_name: 'Francis Ogaba',
    tl_email: 'david.king@curasel.com',
    tl_name: 'David K.',
    hr_email: 'hr@curasel.com',
    employment_date: 'April 14, 2022',
    team: 'Tech',
    role: 'UI Designer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 4,
    annual_balance: 10,
    sick_entitlement: 7,
    sick_taken: 2,
    sick_balance: 5,
  },
  {
    email: 'george.mensah@curasel.com',
    full_name: 'George Mensah',
    tl_email: 'nana.boateng@curasel.com',
    tl_name: 'Nana B.',
    hr_email: 'hr@curasel.com',
    employment_date: 'October 11, 2024',
    team: 'Ops',
    role: 'Ops Trainee',
    country: 'Ghana',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'rose.adedeji@curasel.com',
    full_name: 'Rose Adedeji',
    tl_email: 'halima.idris@curasel.com',
    tl_name: 'Halima I.',
    hr_email: 'hr@curasel.com',
    employment_date: 'March 19, 2024',
    team: 'Support',
    role: 'Support Officer',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'timothy.eko@curasel.com',
    full_name: 'Timothy Eko',
    tl_email: 'ka@curacel.com',
    tl_name: 'Kabiru A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'September 9, 2023',
    team: 'Ops',
    role: 'Ops Analyst',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
  },
  {
    email: 'lekan.bello@curasel.com',
    full_name: 'Lekan Bello',
    tl_email: 'chioma.ude@curasel.com',
    tl_name: 'Chioma U.',
    hr_email: 'hr@curasel.com',
    employment_date: 'March 5, 2021',
    team: 'Finance',
    role: 'Finance Manager',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 5,
    annual_balance: 9,
    sick_entitlement: 7,
    sick_taken: 2,
    sick_balance: 5,
  },
  {
    email: 'teni.adams@curasel.com',
    full_name: 'Teni Adams',
    tl_email: '',
    tl_name: '',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 15, 2020',
    team: 'Executive',
    role: 'COO',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
  {
    email: 'hr@curasel.com',
    full_name: 'HR Admin',
    tl_email: 'teni.adams@curasel.com',
    tl_name: 'Teni A.',
    hr_email: 'hr@curasel.com',
    employment_date: 'January 1, 2020',
    team: 'Human Resources',
    role: 'HR Manager',
    country: 'Nigeria',
    year: 2025,
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
  },
];

// Build employees with roles
export const EMPLOYEES: Employee[] = rawEmployees.map(emp => ({
  ...emp,
  user_role: determineUserRole(emp.email, rawEmployees),
  profile_image: `https://api.dicebear.com/9.x/personas/svg?seed=${emp.full_name.replace(' ', '')}`,
}));

// Helper to get employee by email
export function getEmployeeByEmail(email: string): Employee | undefined {
  return EMPLOYEES.find(emp => emp.email === email);
}

// Helper to get team members (employees who report to this person)
export function getTeamMembers(tlEmail: string): Employee[] {
  return EMPLOYEES.filter(emp => emp.tl_email === tlEmail);
}

// Get all team leads
export function getTeamLeads(): Employee[] {
  return EMPLOYEES.filter(emp => emp.user_role === 'TeamLead');
}

// Pre-created demo accounts for sign-in
export const DEMO_ACCOUNTS = {
  employee: EMPLOYEES.find(e => e.email === 'amina.okoro@curasel.com')!,
  teamLead: EMPLOYEES.find(e => e.email === 'ka@curacel.com')!,
  hr: EMPLOYEES.find(e => e.email === 'hr@curasel.com')!,
  exec: EMPLOYEES.find(e => e.email === 'femi.adeola@curasel.com')!,
};

// Leave Requests with various statuses - includes historical data for rich demo experience
export const LEAVE_REQUESTS: LeaveRequest[] = [
  // ==================== AMINA OKORO (Employee Demo Account) ====================
  // Current pending request
  {
    request_id: 'REQ-2025-001',
    full_name: 'Amina Okoro',
    email: 'amina.okoro@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-20',
    start_date: '2025-12-02',
    end_date: '2025-12-06',
    days_requested: 5,
    days_before_request: 12,
    handover_link: 'https://docs.google.com/document/d/handover-amina-dec',
    status: 'pending',
    tl_name: 'Tunde B.',
    tl_email: 'tunde.balogun@curasel.com',
    tl_status: 'pending',
    tl_decision_date: '',
    tl_comment: '',
    hr_email: 'hr@curasel.com',
    hr_status: '',
    hr_decision_date: '',
    hr_comment: '',
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
    timestamp: '2025-11-20T09:30:00Z',
  },
  // Amina's historical approved leave - August 2025
  {
    request_id: 'REQ-2025-011',
    full_name: 'Amina Okoro',
    email: 'amina.okoro@curasel.com',
    leave_type: 'annual',
    request_date: '2025-07-25',
    start_date: '2025-08-11',
    end_date: '2025-08-15',
    days_requested: 5,
    days_before_request: 17,
    handover_link: 'https://docs.google.com/document/d/handover-amina-aug',
    status: 'approved',
    tl_name: 'Tunde B.',
    tl_email: 'tunde.balogun@curasel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-07-26',
    tl_comment: 'Approved. Enjoy your break!',
    hr_email: 'hr@curasel.com',
    hr_status: 'approved',
    hr_decision_date: '2025-07-27',
    hr_comment: 'Approved.',
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
    timestamp: '2025-07-25T11:00:00Z',
  },
  // Amina's sick leave - March 2025
  {
    request_id: 'REQ-2025-012',
    full_name: 'Amina Okoro',
    email: 'amina.okoro@curasel.com',
    leave_type: 'sick',
    request_date: '2025-03-10',
    start_date: '2025-03-10',
    end_date: '2025-03-11',
    days_requested: 2,
    days_before_request: 0,
    handover_link: '',
    status: 'approved',
    tl_name: 'Tunde B.',
    tl_email: 'tunde.balogun@curasel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-03-10',
    tl_comment: 'Get well soon.',
    hr_email: 'hr@curasel.com',
    hr_status: 'approved',
    hr_decision_date: '2025-03-10',
    hr_comment: 'Approved.',
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
    timestamp: '2025-03-10T07:30:00Z',
  },
  // Amina's approved leave - May 2025
  {
    request_id: 'REQ-2025-013',
    full_name: 'Amina Okoro',
    email: 'amina.okoro@curasel.com',
    leave_type: 'annual',
    request_date: '2025-04-28',
    start_date: '2025-05-19',
    end_date: '2025-05-23',
    days_requested: 5,
    days_before_request: 21,
    handover_link: 'https://docs.google.com/document/d/handover-amina-may',
    status: 'approved',
    tl_name: 'Tunde B.',
    tl_email: 'tunde.balogun@curasel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-04-29',
    tl_comment: 'Have a great holiday!',
    hr_email: 'hr@curasel.com',
    hr_status: 'approved',
    hr_decision_date: '2025-04-30',
    hr_comment: 'Approved.',
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 2,
    sick_balance: 5,
    timestamp: '2025-04-28T09:00:00Z',
  },
  // Amina's declined request - February 2025
  {
    request_id: 'REQ-2025-014',
    full_name: 'Amina Okoro',
    email: 'amina.okoro@curasel.com',
    leave_type: 'annual',
    request_date: '2025-02-10',
    start_date: '2025-02-14',
    end_date: '2025-02-14',
    days_requested: 1,
    days_before_request: 4,
    handover_link: '',
    status: 'declined',
    tl_name: 'Tunde B.',
    tl_email: 'tunde.balogun@curasel.com',
    tl_status: 'declined',
    tl_decision_date: '2025-02-11',
    tl_comment: 'We have a critical deployment scheduled for this day. Please choose another date.',
    hr_email: 'hr@curasel.com',
    hr_status: '',
    hr_decision_date: '',
    hr_comment: '',
    annual_entitlement: 14,
    annual_taken: 0,
    annual_balance: 14,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
    timestamp: '2025-02-10T14:00:00Z',
  },
  // Pending HR approval (TL approved)
  {
    request_id: 'REQ-2025-002',
    full_name: 'James Owen',
    email: 'james.owen@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-15',
    start_date: '2025-11-25',
    end_date: '2025-11-29',
    days_requested: 5,
    days_before_request: 10,
    handover_link: 'https://docs.google.com/document/d/handover-james-nov',
    status: 'pending_hr',
    tl_name: 'Kabiru A.',
    tl_email: 'ka@curacel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-11-16',
    tl_comment: 'Approved. Good handover document.',
    hr_email: 'hr@curasel.com',
    hr_status: '',
    hr_decision_date: '',
    hr_comment: '',
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
    timestamp: '2025-11-15T14:20:00Z',
  },
  // Fully approved
  {
    request_id: 'REQ-2025-003',
    full_name: 'Grace Tamuno',
    email: 'grace.tamuno@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-01',
    start_date: '2025-11-18',
    end_date: '2025-11-22',
    days_requested: 5,
    days_before_request: 17,
    handover_link: 'https://docs.google.com/document/d/handover-grace-nov',
    status: 'approved',
    tl_name: 'Chioma U.',
    tl_email: 'chioma.ude@curasel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-11-02',
    tl_comment: 'Enjoy your time off!',
    hr_email: 'hr@curasel.com',
    hr_status: 'approved',
    hr_decision_date: '2025-11-03',
    hr_comment: 'Approved.',
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 2,
    sick_balance: 5,
    timestamp: '2025-11-01T10:00:00Z',
  },
  // TL Declined
  {
    request_id: 'REQ-2025-004',
    full_name: 'Victor Akin',
    email: 'victor.akin@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-10',
    start_date: '2025-11-15',
    end_date: '2025-11-16',
    days_requested: 2,
    days_before_request: 5,
    handover_link: '',
    status: 'declined',
    tl_name: 'Susan O.',
    tl_email: 'susan.obieze@curasel.com',
    tl_status: 'declined',
    tl_decision_date: '2025-11-11',
    tl_comment: 'Annual leave must be requested at least 7 days in advance. Please resubmit with proper notice.',
    hr_email: 'hr@curasel.com',
    hr_status: '',
    hr_decision_date: '',
    hr_comment: '',
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
    timestamp: '2025-11-10T16:45:00Z',
  },
  // HR Declined
  {
    request_id: 'REQ-2025-005',
    full_name: 'Tolulope Femi',
    email: 'tolulope.femi@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-05',
    start_date: '2025-12-20',
    end_date: '2025-12-31',
    days_requested: 8,
    days_before_request: 45,
    handover_link: 'https://docs.google.com/document/d/handover-tolu-dec',
    status: 'hr_declined',
    tl_name: 'Tunde B.',
    tl_email: 'tunde.balogun@curasel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-11-06',
    tl_comment: 'Approved from team perspective.',
    hr_email: 'hr@curasel.com',
    hr_status: 'declined',
    hr_decision_date: '2025-11-07',
    hr_comment: 'Company-wide blackout period during year-end close. Please request alternative dates.',
    annual_entitlement: 14,
    annual_taken: 6,
    annual_balance: 8,
    sick_entitlement: 7,
    sick_taken: 2,
    sick_balance: 5,
    timestamp: '2025-11-05T11:30:00Z',
  },
  // Sick leave (auto-approved pattern)
  {
    request_id: 'REQ-2025-006',
    full_name: 'Doris Ugwu',
    email: 'doris.ugwu@curasel.com',
    leave_type: 'sick',
    request_date: '2025-11-19',
    start_date: '2025-11-19',
    end_date: '2025-11-20',
    days_requested: 2,
    days_before_request: 0,
    handover_link: '',
    status: 'approved',
    tl_name: 'Halima I.',
    tl_email: 'halima.idris@curasel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-11-19',
    tl_comment: 'Get well soon!',
    hr_email: 'hr@curasel.com',
    hr_status: 'approved',
    hr_decision_date: '2025-11-19',
    hr_comment: 'Approved.',
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
    timestamp: '2025-11-19T08:00:00Z',
  },
  // Another pending for Kabiru's team
  {
    request_id: 'REQ-2025-007',
    full_name: 'Hassan Adamu',
    email: 'hassan.adamu@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-21',
    start_date: '2025-12-09',
    end_date: '2025-12-13',
    days_requested: 5,
    days_before_request: 18,
    handover_link: 'https://docs.google.com/document/d/handover-hassan-dec',
    status: 'pending',
    tl_name: 'Kabiru A.',
    tl_email: 'ka@curacel.com',
    tl_status: 'pending',
    tl_decision_date: '',
    tl_comment: '',
    hr_email: 'hr@curasel.com',
    hr_status: '',
    hr_decision_date: '',
    hr_comment: '',
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
    timestamp: '2025-11-21T10:15:00Z',
  },
  // Susan's team member pending
  {
    request_id: 'REQ-2025-008',
    full_name: 'Queen Abasi',
    email: 'queen.abasi@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-20',
    start_date: '2025-12-16',
    end_date: '2025-12-20',
    days_requested: 5,
    days_before_request: 26,
    handover_link: 'https://docs.google.com/document/d/handover-queen-dec',
    status: 'pending',
    tl_name: 'Susan O.',
    tl_email: 'susan.obieze@curasel.com',
    tl_status: 'pending',
    tl_decision_date: '',
    tl_comment: '',
    hr_email: 'hr@curasel.com',
    hr_status: '',
    hr_decision_date: '',
    hr_comment: '',
    annual_entitlement: 14,
    annual_taken: 3,
    annual_balance: 11,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
    timestamp: '2025-11-20T14:00:00Z',
  },
  // Currently on leave (approved, dates in progress)
  {
    request_id: 'REQ-2025-009',
    full_name: 'Remi Ogunleye',
    email: 'remi.ogunleye@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-10',
    start_date: '2025-11-18',
    end_date: '2025-11-25',
    days_requested: 6,
    days_before_request: 8,
    handover_link: 'https://docs.google.com/document/d/handover-remi-nov',
    status: 'approved',
    tl_name: 'Lekan B.',
    tl_email: 'lekan.bello@curasel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-11-11',
    tl_comment: 'Approved.',
    hr_email: 'hr@curasel.com',
    hr_status: 'approved',
    hr_decision_date: '2025-11-12',
    hr_comment: 'Approved.',
    annual_entitlement: 14,
    annual_taken: 1,
    annual_balance: 13,
    sick_entitlement: 7,
    sick_taken: 1,
    sick_balance: 6,
    timestamp: '2025-11-10T09:00:00Z',
  },
  // Pending for HR to review
  {
    request_id: 'REQ-2025-010',
    full_name: 'Felix Ogwo',
    email: 'felix.ogwo@curasel.com',
    leave_type: 'annual',
    request_date: '2025-11-19',
    start_date: '2025-12-05',
    end_date: '2025-12-10',
    days_requested: 4,
    days_before_request: 16,
    handover_link: 'https://docs.google.com/document/d/handover-felix-dec',
    status: 'pending_hr',
    tl_name: 'David K.',
    tl_email: 'david.king@curasel.com',
    tl_status: 'approved',
    tl_decision_date: '2025-11-19',
    tl_comment: 'Good to go.',
    hr_email: 'hr@curasel.com',
    hr_status: '',
    hr_decision_date: '',
    hr_comment: '',
    annual_entitlement: 14,
    annual_taken: 2,
    annual_balance: 12,
    sick_entitlement: 7,
    sick_taken: 0,
    sick_balance: 7,
    timestamp: '2025-11-19T11:30:00Z',
  },
];

// Handover Tasks
export const HANDOVER_TASKS: HandoverTask[] = [
  {
    id: 'HT-001',
    request_id: 'REQ-2025-003',
    title: 'Complete Q4 Claims Report',
    description: 'Finalize the quarterly claims analysis report and submit to finance team. All data is in the shared drive. Contact Chioma for any clarifications.',
    owner_email: 'grace.tamuno@curasel.com',
    owner_name: 'Grace Tamuno',
    assignee_email: 'oluchi.mbah@curasel.com',
    assignee_name: 'Oluchi Mbah',
    priority: 'high',
    status: 'in_progress',
    due_date: '2025-11-22',
    created_date: '2025-11-01',
    completed_date: '',
  },
  {
    id: 'HT-002',
    request_id: 'REQ-2025-003',
    title: 'Monitor daily claim submissions',
    description: 'Review and process incoming claims during absence. Use the standard checklist for processing.',
    owner_email: 'grace.tamuno@curasel.com',
    owner_name: 'Grace Tamuno',
    assignee_email: 'vivian.ukonu@curasel.com',
    assignee_name: 'Vivian Ukonu',
    priority: 'high',
    status: 'acknowledged',
    due_date: '2025-11-22',
    created_date: '2025-11-01',
    completed_date: '',
  },
  {
    id: 'HT-003',
    request_id: 'REQ-2025-009',
    title: 'Process vendor payments',
    description: 'Complete pending vendor payment approvals. All invoices are pre-approved. Just need final sign-off.',
    owner_email: 'remi.ogunleye@curasel.com',
    owner_name: 'Remi Ogunleye',
    assignee_email: 'yusuf.musa@curasel.com',
    assignee_name: 'Yusuf Musa',
    priority: 'high',
    status: 'in_progress',
    due_date: '2025-11-25',
    created_date: '2025-11-10',
    completed_date: '',
  },
  {
    id: 'HT-004',
    request_id: 'REQ-2025-002',
    title: 'Update ops dashboard metrics',
    description: 'Ensure daily metrics are updated in the team dashboard. Dashboard link in team wiki.',
    owner_email: 'james.owen@curasel.com',
    owner_name: 'James Owen',
    assignee_email: 'nana.boateng@curasel.com',
    assignee_name: 'Nana Boateng',
    priority: 'medium',
    status: 'pending',
    due_date: '2025-11-29',
    created_date: '2025-11-15',
    completed_date: '',
  },
  {
    id: 'HT-005',
    request_id: 'REQ-2025-007',
    title: 'Coordinate with logistics team',
    description: 'Handle any urgent logistics requests during absence. Contact list in shared folder.',
    owner_email: 'hassan.adamu@curasel.com',
    owner_name: 'Hassan Adamu',
    assignee_email: 'timothy.eko@curasel.com',
    assignee_name: 'Timothy Eko',
    priority: 'medium',
    status: 'pending',
    due_date: '2025-12-13',
    created_date: '2025-11-21',
    completed_date: '',
  },
  {
    id: 'HT-006',
    request_id: 'REQ-2025-001',
    title: 'Handle field support tickets',
    description: 'Monitor and respond to urgent field support tickets. Escalate critical issues to Tunde.',
    owner_email: 'amina.okoro@curasel.com',
    owner_name: 'Amina Okoro',
    assignee_email: 'abdul.kareem@curasel.com',
    assignee_name: 'Abdul Kareem',
    priority: 'high',
    status: 'pending',
    due_date: '2025-12-06',
    created_date: '2025-11-20',
    completed_date: '',
  },
];

// Post-Leave Context Notes
export const POST_LEAVE_NOTES: PostLeaveNote[] = [
  {
    id: 'PLN-001',
    request_id: 'REQ-2025-003',
    employee_email: 'grace.tamuno@curasel.com',
    employee_name: 'Grace Tamuno',
    content: 'While you were away:\n- Q4 report was submitted on time\n- New claim processing guidelines were released\n- Team meeting notes from Nov 20 in shared drive\n- 3 escalated claims need your review',
    created_at: '2025-11-22T16:00:00Z',
    created_by_email: 'oluchi.mbah@curasel.com',
    created_by_name: 'Oluchi Mbah',
  },
];

// Notifications
export const NOTIFICATIONS: Notification[] = [
  {
    id: 'NOTIF-001',
    user_email: 'ka@curacel.com',
    type: 'approval',
    title: 'New Leave Request',
    message: 'Hassan Adamu has submitted a leave request for Dec 9-13 requiring your approval.',
    action_url: '/team/approvals',
    read: false,
    created_at: '2025-11-21T10:15:00Z',
    related_request_id: 'REQ-2025-007',
  },
  {
    id: 'NOTIF-002',
    user_email: 'ka@curacel.com',
    type: 'approval',
    title: 'New Leave Request',
    message: 'James Owen has submitted a leave request for Nov 25-29 requiring your approval.',
    action_url: '/team/approvals',
    read: true,
    created_at: '2025-11-15T14:20:00Z',
    related_request_id: 'REQ-2025-002',
  },
  {
    id: 'NOTIF-003',
    user_email: 'hr@curasel.com',
    type: 'approval',
    title: 'Leave Request Awaiting HR Review',
    message: 'James Owen\'s leave request has been approved by Team Lead and requires HR approval.',
    action_url: '/hr/requests',
    read: false,
    created_at: '2025-11-16T10:00:00Z',
    related_request_id: 'REQ-2025-002',
  },
  {
    id: 'NOTIF-004',
    user_email: 'hr@curasel.com',
    type: 'approval',
    title: 'Leave Request Awaiting HR Review',
    message: 'Felix Ogwo\'s leave request has been approved by Team Lead and requires HR approval.',
    action_url: '/hr/requests',
    read: false,
    created_at: '2025-11-19T12:00:00Z',
    related_request_id: 'REQ-2025-010',
  },
  {
    id: 'NOTIF-005',
    user_email: 'james.owen@curasel.com',
    type: 'approval',
    title: 'Leave Request Approved by TL',
    message: 'Your leave request for Nov 25-29 has been approved by Kabiru A. and sent to HR for final approval.',
    action_url: '/leave/history',
    read: false,
    created_at: '2025-11-16T10:00:00Z',
    related_request_id: 'REQ-2025-002',
  },
  {
    id: 'NOTIF-006',
    user_email: 'victor.akin@curasel.com',
    type: 'rejection',
    title: 'Leave Request Declined',
    message: 'Your leave request for Nov 15-16 has been declined by Susan O. Reason: Annual leave must be requested at least 7 days in advance.',
    action_url: '/leave/history',
    read: false,
    created_at: '2025-11-11T09:00:00Z',
    related_request_id: 'REQ-2025-004',
  },
  {
    id: 'NOTIF-007',
    user_email: 'oluchi.mbah@curasel.com',
    type: 'handover',
    title: 'New Handover Task Assigned',
    message: 'Grace Tamuno has assigned you a handover task: Complete Q4 Claims Report',
    action_url: '/handovers',
    read: true,
    created_at: '2025-11-01T10:30:00Z',
    related_request_id: 'REQ-2025-003',
  },
  {
    id: 'NOTIF-008',
    user_email: 'grace.tamuno@curasel.com',
    type: 'catchup',
    title: 'Post-Leave Notes Available',
    message: 'Oluchi Mbah has added catch-up notes for your return from leave.',
    action_url: '/handovers',
    read: false,
    created_at: '2025-11-22T16:00:00Z',
    related_request_id: 'REQ-2025-003',
  },
];

// Utility functions
export function calculateWorkingDays(startDate: string, endDate: string): number {
  const start = new Date(startDate);
  const end = new Date(endDate);
  let count = 0;
  const current = new Date(start);

  while (current <= end) {
    const dayOfWeek = current.getDay();
    if (dayOfWeek !== 0 && dayOfWeek !== 6) {
      count++;
    }
    current.setDate(current.getDate() + 1);
  }

  return count;
}

export function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

export function getStatusColor(status: string): string {
  switch (status) {
    case 'pending':
      return 'bg-yellow-100 text-yellow-800';
    case 'pending_hr':
      return 'bg-blue-100 text-blue-800';
    case 'approved':
      return 'bg-green-100 text-green-800';
    case 'declined':
    case 'hr_declined':
      return 'bg-red-100 text-red-800';
    default:
      return 'bg-gray-100 text-gray-800';
  }
}

export function getStatusLabel(status: string): string {
  switch (status) {
    case 'pending':
      return 'Pending TL';
    case 'pending_hr':
      return 'Pending HR';
    case 'approved':
      return 'Approved';
    case 'declined':
      return 'TL Declined';
    case 'hr_declined':
      return 'HR Declined';
    default:
      return status;
  }
}
